-- Run this migration in the Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  bio text not null default '',
  location text not null default '',
  skills text not null default '',
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.email, '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.saved_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id text not null,
  title text not null,
  company text not null,
  location text not null default '',
  type text not null default '',
  salary text not null default '',
  created_at timestamptz not null default now(),
  unique (user_id, job_id)
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id text not null,
  title text not null,
  company text not null,
  location text not null default '',
  type text not null default '',
  salary text not null default '',
  applicant text not null default '',
  phone text not null,
  cv text not null default '',
  "coverLetter" text not null,
  status text not null default 'Applied',
  created_at timestamptz not null default now(),
  unique (user_id, job_id)
);

alter table public.profiles enable row level security;
alter table public.saved_jobs enable row level security;
alter table public.applications enable row level security;

create policy "Users manage their profile"
  on public.profiles for all
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Users manage their saved jobs"
  on public.saved_jobs for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users manage their applications"
  on public.applications for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);