-- Run this migration in the Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  role text not null default 'job_seeker',
  bio text not null default '',
  location text not null default '',
  skills text not null default '',
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'role', 'job_seeker')
  )
  on conflict (id) do update
    set full_name = excluded.full_name,
        email = excluded.email,
        role = excluded.role;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  employer_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  company text not null,
  location text not null default '',
  type text not null default '',
  salary text not null default '',
  description text not null default '',
  responsibilities jsonb not null default '[]'::jsonb,
  requirements jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, job_id)
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  phone text not null,
  cv text not null default '',
  cv_text text not null default '',
  cover_letter text not null,
  status text not null default 'Applied',
  created_at timestamptz not null default now(),
  unique (user_id, job_id)
);

alter table public.applications
  add column if not exists cv_text text not null default '';

alter table public.profiles enable row level security;
alter table public.jobs enable row level security;
alter table public.saved_jobs enable row level security;
alter table public.applications enable row level security;

create policy "Users manage their profile"
  on public.profiles for all
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Employers view applicant profiles"
  on public.profiles for select
  using (
    exists (
      select 1
      from public.applications
      join public.jobs on jobs.id = applications.job_id
      where applications.user_id = profiles.id
        and jobs.employer_id = auth.uid()
    )
  );

create policy "Anyone can view jobs"
  on public.jobs for select
  using (true);

create policy "Employers can post jobs"
  on public.jobs for insert
  with check (
    auth.uid() = employer_id
    and exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'employer'
    )
  );

create policy "Employers manage their jobs"
  on public.jobs for update
  using (auth.uid() = employer_id)
  with check (auth.uid() = employer_id);

create policy "Employers delete their jobs"
  on public.jobs for delete
  using (auth.uid() = employer_id);

drop policy if exists "Users manage their saved jobs" on public.saved_jobs;

create policy "Job seekers manage their saved jobs"
  on public.saved_jobs for all
  using (
    auth.uid() = user_id
    and exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'job_seeker'
    )
  )
  with check (
    auth.uid() = user_id
    and exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'job_seeker'
    )
  );

drop policy if exists "Users manage their applications" on public.applications;
create policy "Users manage their applications"
  on public.applications for insert
  with check (
    auth.uid() = user_id
    and exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'job_seeker'
    )
  );

create policy "Applicants view their applications"
  on public.applications for select
  using (auth.uid() = user_id);

create policy "Employers view applications for their jobs"
  on public.applications for select
  using (
    exists (
      select 1
      from public.jobs
      where jobs.id = applications.job_id
        and jobs.employer_id = auth.uid()
    )
  );

create policy "Employers delete applications for their jobs"
  on public.applications for delete
  using (
    exists (
      select 1
      from public.jobs
      where jobs.id = applications.job_id
        and jobs.employer_id = auth.uid()
    )
  );

create policy "Employers update application status"
  on public.applications for update
  using (
    exists (
      select 1
      from public.jobs
      where jobs.id = applications.job_id
        and jobs.employer_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.jobs
      where jobs.id = applications.job_id
        and jobs.employer_id = auth.uid()
    )
  );